/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

import com.app.control.WindowsManager;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import org.tinylog.Logger;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new McWinLookAndFeel());
            WindowsManager windowsManager = new WindowsManager("Registro de estudiantes");
            WindowsManager.localInstance = windowsManager;
            windowsManager.assembleWindow();
            windowsManager.getMainWindow().setVisible(true);
        } catch (Exception ex) {
            Logger.error(ex, ":(");
        }
    }
}
